name: qr_code_scanner
description: A new Flutter project.

version: 1.0.1+2

environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_svg: ^2.0.7
  json_annotation: ^4.8.1
  font_awesome_flutter: ^10.5.0
  path_provider: ^2.1.0
  barcode_scan2: ^4.2.4
  qr_flutter: ^4.1.0
  esys_flutter_share_plus: ^2.2.0
  launch_review: ^3.0.1
  url_launcher: ^6.1.12
  fluttertoast: ^8.2.2
  flutter_markdown: ^0.6.17+1
  permission_handler: ^10.4.3
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  build_runner: ^2.4.6
  json_serializable: ^6.7.1

  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assests/images/qrcode.png"
  image_path_android: "assests/images/qrcode.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assests/icons/
    - assests/images/icon.png
    - assests/qr_generators.json

  fonts:
    - family: Righteous
      fonts:
        - asset: assests/fonts/Righteous-Regular.ttf

