name: qr_code_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_svg: ^0.14.4
  json_annotation: ^2.0.0
  font_awesome_flutter: ^8.5.0
  path_provider: ^1.6.5
  barcode_scan: ^2.0.1
  qr_flutter: ^3.2.0
  esys_flutter_share: ^1.0.2
  launch_review: ^2.0.0
  url_launcher: ^5.1.4
  fluttertoast: ^3.1.3
  flutter_markdown: ^0.3.4
  simple_permissions: ^0.1.9
  flutter_launcher_icons: ^0.7.4

  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assests/images/qrcode.png"
  image_path_android: "assests/images/qrcode.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assests/icons/
    - assests/images/icon.png
    - assests/qr_generators.json

  fonts:
    - family: Righteous
      fonts:
        - asset: assests/fonts/Righteous-Regular.ttf

