name: qr_code_scanner
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter_svg: ^0.14.4
  json_annotation: ^2.0.0
  font_awesome_flutter: ^8.5.0
  path_provider: ^0.4.1
  barcode_scan: ^1.0.0
  qr_flutter: ^3.1.0
  share: ^0.6.2+1
  launch_review: ^2.0.0
  url_launcher: ^5.1.4
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^2.0.0

  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assests/icons/
    - assests/qr_generators.json

  fonts:
    - family: Righteous
      fonts:
        - asset: assests/fonts/Righteous-Regular.ttf

